### ISSUE TITLE
Can't install New-Minty

### ISSUE THREAD

**Issue by Gasotin** [zagortenay333/new-minty#1]
I tried to install your theme and this happened:

[10:23:37] Using gulpfile ~/Downloads/New-Minty/cinnamon/gulpfile.js
[10:23:37] Starting 'install'...
[10:23:37] 'install' errored after 164 μs
[10:23:37] Error: EISDIR, illegal operation on a directory '/home/gaso/.themes/New-Minty'
    at Object.fs.unlinkSync (fs.js:765:18)
    at Gulp.<anonymous> (/home/gaso/Downloads/New-Minty/cinnamon/gulpfile.js:53:12)
    at module.exports (/home/gaso/Downloads/New-Minty/cinnamon/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/gaso/Downloads/New-Minty/cinnamon/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/gaso/Downloads/New-Minty/cinnamon/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/gaso/Downloads/New-Minty/cinnamon/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)

**Comment by zagortenay333** [comment]
For now, make sure that there is no `New-Minty` folder in your `.themes` dir prior to running gulp.

I wrote this in the README.

**Comment by zagortenay333** [comment]
OK, I updated the `gulpfile.js`. Now it will delete any existing files/folders named `New-Minty` prior to making a link.
